wakawaka-CONTACTO/contacto-server

user-service/build.gradle, user-service/gradle/wrapper/gradle-wrapper.properties, user-service/src/main/java/org/kiru/user/auth/api/KakaoApiClient.java, user-service/src/main/java/org/kiru/user/auth/api/KakaoAuthApi.java, user-service/src/main/java/org/kiru/user/auth/argumentresolve/UserId.java, user-service/src/main/java/org/kiru/user/auth/argumentresolve/UserIdArgumentResolver.java, user-service/src/main/java/org/kiru/user/auth/controller/AuthController.java, user-service/src/main/java/org/kiru/user/auth/jwt/JwtGenerator.java, user-service/src/main/java/org/kiru/user/auth/jwt/JwtProperties.java, user-service/src/main/java/org/kiru/user/auth/jwt/JwtProvider.java, user-service/src/main/java/org/kiru/user/auth/jwt/RefreshTokenGenerator.java, user-service/src/main/java/org/kiru/user/auth/jwt/Token.java, user-service/src/main/java/org/kiru/user/auth/jwt/refreshtoken/repository/RefreshTokenRepository.java, user-service/src/main/java/org/kiru/user/auth/kakao/KaKaoDto.java, user-service/src/main/java/org/kiru/user/auth/kakao/KakaoAuthService.java, user-service/src/main/java/org/kiru/user/auth/kakao/KakaoTokenResponse.java, user-service/src/main/java/org/kiru/user/common/FailureResponse.java, user-service/src/main/java/org/kiru/user/common/GlobalExceptionHandler.java, user-service/src/main/java/org/kiru/user/config/QueryDslConfig.java, user-service/src/main/java/org/kiru/user/config/WebConfig.java, user-service/src/main/java/org/kiru/user/exception/BadRequestException.java, user-service/src/main/java/org/kiru/user/exception/ConflictException.java, user-service/src/main/java/org/kiru/user/exception/ContactoException.java, user-service/src/main/java/org/kiru/user/exception/EntityNotFoundException.java, user-service/src/main/java/org/kiru/user/exception/ForbiddenException.java, user-service/src/main/java/org/kiru/user/exception/InvalidValueException.java, user-service/src/main/java/org/kiru/user/exception/UnauthorizedException.java, user-service/src/main/java/org/kiru/user/exception/code/FailureCode.java, user-service/src/main/java/org/kiru/user/exception/code/SuccessCode.java
=> User-Service 구현 - Feat/#3

chat-service/build.gradle, chat-service/gradle/wrapper/gradle-wrapper.properties, chat-service/src/main/java/org/kiru/chat/ChatServiceApplication.java, chat-service/src/main/java/org/kiru/chat/adapter/in/web/ChatRoomController.java, chat-service/src/main/java/org/kiru/chat/adapter/in/web/CreateChatRoomRequest.java, chat-service/src/main/java/org/kiru/chat/adapter/in/web/CreateChatRoomResponse.java, chat-service/src/main/java/org/kiru/chat/application/port/in/AddParticipantUseCase.java, chat-service/src/main/java/org/kiru/chat/application/port/in/CreateRoomUseCase.java, chat-service/src/main/java/org/kiru/chat/application/port/in/GetChatRoomUseCase.java, chat-service/src/main/java/org/kiru/chat/application/port/in/SendMessageUseCase.java, chat-service/src/main/java/org/kiru/chat/application/service/ChatService.java, chat-service/src/main/java/org/kiru/chat/config/argumentresolve/UserId.java, chat-service/src/main/java/org/kiru/chat/config/argumentresolve/UserIdArgumentResolver.java, chat-service/src/main/java/org/kiru/chat/config/config/WebConfig.java, chat-service/src/main/java/org/kiru/chat/config/websocket/CorsConfigure.java, chat-service/src/main/java/org/kiru/chat/config/websocket/WebSocketConfig.java
- 나의 전체 채팅방 조회
- 채팅방 1개 조회 
- 채팅방 접속
- 메세지 전송
- 채팅방 참여
=> [FEAT] Chat service 구현 - #11

user-service/src/main/java/org/kiru/user/auth/mail/service/MailService.java
⛳️ **작업한 브랜치**
- feature/#20
👷 **작업한 내용**
- Resolved: #20
=> [FIX] Mail인증 6자리 코드 변경 - #20

.gitignore, chat-service/src/main/java/org/kiru/chat/config/websocket/WebSocketConfig.java, core/src/main/java/org/kiru/core/user/user/domain/User.java, core/src/main/java/org/kiru/core/user/user/entity/UserJpaEntity.java, core/src/main/java/org/kiru/core/user/userPortfolioImg/entity/UserPortfolioImg.java, core/src/main/java/org/kiru/core/user/userPurpose/domain/PurposeType.java, user-service/src/main/java/org/kiru/user/config/IntegerBinder.java, user-service/src/main/java/org/kiru/user/config/WebConfig.java, user-service/src/main/java/org/kiru/user/external/s3/ImageService.java, user-service/src/main/java/org/kiru/user/portfolio/repository/UserPortfolioImgRepository.java, user-service/src/main/java/org/kiru/user/portfolio/service/PortfolioService.java, user-service/src/main/java/org/kiru/user/user/controller/UserLoginController.java, user-service/src/main/java/org/kiru/user/user/controller/UserUpdateController.java, user-service/src/main/java/org/kiru/user/user/dto/request/UserSignUpReq.java, user-service/src/main/java/org/kiru/user/user/dto/request/UserUpdateDto.java, user-service/src/main/java/org/kiru/user/user/repository/UserPortfolioRepository.java, user-service/src/main/java/org/kiru/user/user/repository/UserPurposeRepository.java, user-service/src/main/java/org/kiru/user/user/repository/UserRepository.java, user-service/src/main/java/org/kiru/user/user/repository/UserTalentRepository.java, user-service/src/main/java/org/kiru/user/user/service/UserService.java, user-service/src/main/java/org/kiru/user/userlike/repository/UserLikeRepository.java
⛳️ **작업한 브랜치**
- feature/#22
👷 **작업한 내용**
- Resolved: #22
=> [FEAT] 유저 추천 로직 및 Update 추가 - #22

chat-service/src/main/java/org/kiru/chat/application/port/out/GetAllMessageByRoomQuery.java, chat-service/src/main/java/org/kiru/chat/application/service/ChatService.java, user-service/src/main/java/org/kiru/user/auth/controller/AuthController.java, user-service/src/main/java/org/kiru/user/auth/jwt/JwtProvider.java, user-service/src/main/java/org/kiru/user/auth/jwt/RefreshTokenGenerator.java, user-service/src/main/java/org/kiru/user/auth/jwt/refreshtoken/repository/RefreshTokenAdapter.java, user-service/src/main/java/org/kiru/user/auth/jwt/refreshtoken/repository/RefreshTokenRepository.java, user-service/src/main/java/org/kiru/user/auth/jwt/refreshtoken/repository/RefreshTokenRepositoryCustom.java, user-service/src/main/java/org/kiru/user/config/StringToIntegerListConverter.java, user-service/src/main/java/org/kiru/user/config/WebConfig.java, user-service/src/main/java/org/kiru/user/user/adapter/UserRepositoryAdapter.java, user-service/src/main/java/org/kiru/user/user/controller/UserLoginController.java, user-service/src/main/java/org/kiru/user/user/dto/request/PurposeTypeDeserializer.java, user-service/src/main/java/org/kiru/user/user/dto/request/UserUpdateDto.java, user-service/src/main/java/org/kiru/user/user/repository/UserCacheRepository.java, user-service/src/main/java/org/kiru/user/user/repository/UserPurposeRepository.java, user-service/src/main/java/org/kiru/user/user/repository/UserRepository.java, user-service/src/main/java/org/kiru/user/user/service/AuthService.java, user-service/src/main/java/org/kiru/user/user/service/UserService.java, user-service/src/main/java/org/kiru/user/user/service/in/GetUserMainPageUseCase.java
⛳️ **작업한 브랜치**
- feature/#25
👷 **작업한 내용**
- Resolved: #25
=> [FEAT] reissue API 추가 및 user update로직 개선 - #25

user-service/src/main/java/org/kiru/user/portfolio/adapter/UserPortfolioRepositoryAdapter.java, user-service/src/main/java/org/kiru/user/portfolio/dto/res/UserPortfolioResDto.java, user-service/src/main/java/org/kiru/user/portfolio/repository/UserPortfolioImgRepository.java, user-service/src/main/java/org/kiru/user/portfolio/service/PortfolioService.java, user-service/src/main/java/org/kiru/user/user/repository/UserPortfolioRepository.java
⛳️ **작업한 브랜치**
- feature/#27
👷 **작업한 내용**
- Resolved: #27
=> [REFACTOR] 메인 조회 로직 개선 - #27

.gitignore, user-service/src/main/java/org/kiru/user/portfolio/service/out/GetUserPortfoliosQuery.java, user-service/src/main/java/org/kiru/user/user/service/out/UserQueryWithCache.java, user-service/src/main/java/org/kiru/user/user/service/out/UserUpdateUseCase.java
⛳️ **작업한 브랜치**
- feature/#이슈번호
👷 **작업한 내용**
- Resolved: #이슈번호
=> [fix] out 폴더 파일 - #27

user-service/src/main/java/org/kiru/user/portfolio/service/out/GetUserPortfoliosQuery.java
⛳️ **작업한 브랜치**
- feature/#27
👷 **작업한 내용**
- Resolved: #27
=> [FIX] 구문 제거 - #27

user-service/src/main/java/org/kiru/user/portfolio/service/out/GetUserPortfoliosQuery.java
Reverts wakawaka-CONTACTO/contacto-server#30
=> Revert "[FIX] 구문 제거 - #27"

chat-service/src/main/java/org/kiru/chat/adapter/in/web/ChatRoomController.java, chat-service/src/main/java/org/kiru/chat/adapter/in/web/res/ChatRoomResponse.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/ChatRoomRepositoryAdapter.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/UserJoinChatRoomRepository.java, core/src/main/java/org/kiru/core/chat/chatroom/domain/ChatRoom.java, core/src/main/java/org/kiru/core/chat/message/domain/Message.java, core/src/main/java/org/kiru/core/chat/message/entity/MessageJpaEntity.java, user-service/src/main/java/org/kiru/user/user/controller/UserController.java, user-service/src/main/java/org/kiru/user/user/dto/response/ChatRoomListResponse.java, user-service/src/main/java/org/kiru/user/user/dto/response/ChatRoomResponse.java, user-service/src/main/java/org/kiru/user/user/dto/response/GetMyInfoResponse.java, user-service/src/main/java/org/kiru/user/user/dto/response/MessageResponse.java, user-service/src/main/java/org/kiru/user/user/repository/UserPortfolioRepository.java, user-service/src/main/java/org/kiru/user/user/repository/UserRepository.java, user-service/src/main/java/org/kiru/user/user/service/UserService.java
⛳️ **작업한 브랜치**
- feature/#32
👷 **작업한 내용**
- Resolved: #32
=> [FEAT&FIX] 유저 채팅방 리스트 반환값 및 채팅 접속 읽은 메세지 추가 - #32

chat-service/src/main/java/org/kiru/chat/config/websocket/WebSocketConfig.java, user-service/src/main/java/org/kiru/user/portfolio/service/PortfolioService.java, user-service/src/main/java/org/kiru/user/user/controller/UserController.java, user-service/src/main/java/org/kiru/user/user/service/UserService.java
⛳️ **작업한 브랜치**
- feature/#32
👷 **작업한 내용**
- Resolved: #32
=> [FIX] 나 추천 제외 - #32

user-service/src/main/java/org/kiru/user/external/s3/ImageService.java, user-service/src/main/java/org/kiru/user/user/adapter/UserRepositoryAdapter.java, user-service/src/main/java/org/kiru/user/user/dto/request/UserUpdateDto.java
⛳️ **작업한 브랜치**
- feature/#37
👷 **작업한 내용**
- Resolved: #37
=> [FIX] Update로직 수정 - #37

chat-service/src/main/java/org/kiru/chat/adapter/in/web/ChatRoomController.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/ChatRoomRepositoryAdapter.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/UserJoinChatRoomRepository.java, chat-service/src/main/java/org/kiru/chat/application/port/in/GetAlreadyLikedUserIdsUseCase.java, chat-service/src/main/java/org/kiru/chat/application/port/out/GetAlreadyLikedUserIdsQuery.java, chat-service/src/main/java/org/kiru/chat/application/service/ChatService.java, core/src/main/java/org/kiru/core/user/userlike/entity/UserLike.java, gateway-service/src/main/java/org/kiru/gateway/filter/RouteValidator.java, user-service/src/main/java/org/kiru/user/auth/mail/controller/MailController.java, user-service/src/main/java/org/kiru/user/portfolio/controller/PortfolioController.java, user-service/src/main/java/org/kiru/user/portfolio/service/PortfolioService.java, user-service/src/main/java/org/kiru/user/user/api/ChatApiClient.java, user-service/src/main/java/org/kiru/user/user/controller/UserLoginController.java, user-service/src/main/java/org/kiru/user/user/dto/request/SignHelpDto.java, user-service/src/main/java/org/kiru/user/user/dto/response/SignHelpDtoRes.java, user-service/src/main/java/org/kiru/user/user/repository/UserPurposeRepository.java, user-service/src/main/java/org/kiru/user/user/repository/UserRepository.java, user-service/src/main/java/org/kiru/user/user/service/AuthService.java, user-service/src/main/java/org/kiru/user/userlike/repository/UserLikeAdapter.java, user-service/src/main/java/org/kiru/user/userlike/repository/UserLikeRepository.java
⛳️ **작업한 브랜치**
- feature/#39
👷 **작업한 내용**
- Resolved: #39
=> [FEAT] 이메일 재조회 API 및 유저 추천로직 수정 - #39

core/src/main/java/org/kiru/core/user/user/entity/UserJpaEntity.java, user-service/src/main/java/org/kiru/user/user/adapter/UserRepositoryAdapter.java, user-service/src/main/java/org/kiru/user/user/controller/UserUpdateController.java, user-service/src/main/java/org/kiru/user/user/dto/request/UserUpdatePwdDto.java, user-service/src/main/java/org/kiru/user/user/service/UserService.java, user-service/src/main/java/org/kiru/user/user/service/out/UserUpdateUseCase.java
⛳️ **작업한 브랜치**
- feature/#41
👷 **작업한 내용**
- Resolved: #41
=> [FEAT] user 비밀번호 조회 API - #41

core/src/main/java/org/kiru/core/user/user/entity/UserJpaEntity.java, user-service/src/main/java/org/kiru/user/user/adapter/UserRepositoryAdapter.java, user-service/src/main/java/org/kiru/user/user/controller/UserController.java, user-service/src/main/java/org/kiru/user/user/dto/request/UserSignUpReq.java, user-service/src/main/java/org/kiru/user/user/service/UserService.java
⛳️ **작업한 브랜치**
- feature/#45
👷 **작업한 내용**
- Resolved: #45
=> [FEAT] 유저 삭제 API 구현 - #45

user-service/src/main/java/org/kiru/user/user/adapter/UserRepositoryAdapter.java, user-service/src/main/java/org/kiru/user/user/controller/UserUpdateController.java, user-service/src/main/java/org/kiru/user/user/dto/response/UpdatePwdResponse.java, user-service/src/main/java/org/kiru/user/user/service/UserService.java, user-service/src/main/java/org/kiru/user/user/service/out/UserUpdateUseCase.java
⛳️ **작업한 브랜치**
- feature/#47
👷 **작업한 내용**
- Resolved: #47
=> [FIX] 반환값 변경 - #47

user-service/src/main/java/org/kiru/user/auth/mail/controller/MailController.java, user-service/src/main/java/org/kiru/user/auth/mail/dto/MailCheckResponse.java, user-service/src/main/java/org/kiru/user/auth/mail/service/MailService.java
⛳️ **작업한 브랜치**
- feature/#50
👷 **작업한 내용**
- Resolved: #50
=> [FIX] mail check api 응답 변경 - #50

gateway-service/src/main/resources/static/js/config.js
⛳️ **작업한 브랜치**
- feature/#48
👷 **작업한 내용**
- Resolved: #48
=> [FIX] api 수정 - #48

chat-service/src/main/java/org/kiru/chat/adapter/in/web/ChatRoomController.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/ChatRoomRepository.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/ChatRoomRepositoryAdapter.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/MessageRepository.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/MessageRepositoryAdapter.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/UserJoinChatRoomRepository.java, chat-service/src/main/java/org/kiru/chat/application/port/in/GetChatRoomUseCase.java, chat-service/src/main/java/org/kiru/chat/application/port/in/GetMessageUseCase.java, chat-service/src/main/java/org/kiru/chat/application/port/out/GetAllMessageByRoomQuery.java, chat-service/src/main/java/org/kiru/chat/application/port/out/GetChatRoomQuery.java, chat-service/src/main/java/org/kiru/chat/application/port/out/GetMessageByRoomQuery.java, chat-service/src/main/java/org/kiru/chat/application/service/ChatService.java, core/src/main/java/org/kiru/core/chat/chatroom/entity/ChatRoomJpaEntity.java, gateway-service/src/main/resources/static/user-detail.html, user-service/src/main/java/org/kiru/user/admin/adapter/AdminAdapter.java, user-service/src/main/java/org/kiru/user/admin/controller/AdminController.java, user-service/src/main/java/org/kiru/user/admin/service/AdminService.java, user-service/src/main/java/org/kiru/user/admin/service/out/AdminUserQuery.java, user-service/src/main/java/org/kiru/user/user/api/ChatApiClient.java, user-service/src/main/java/org/kiru/user/user/controller/UserController.java, user-service/src/main/java/org/kiru/user/user/repository/UserPortfolioRepository.java, user-service/src/main/java/org/kiru/user/user/repository/UserRepository.java, user-service/src/main/java/org/kiru/user/user/service/UserService.java
⛳️ **작업한 브랜치**
- feature/#48
👷 **작업한 내용**
- Resolved: #48
=> [FIX] admin 개선 - #48

chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/ChatRoomRepositoryAdapter.java, chat-service/src/main/java/org/kiru/chat/application/port/out/GetChatRoomQuery.java, chat-service/src/main/java/org/kiru/chat/application/service/ChatService.java, user-service/src/main/java/org/kiru/user/common/FeignErrorDecoder.java, user-service/src/main/java/org/kiru/user/config/FeignConfig.java, user-service/src/main/java/org/kiru/user/config/LazyDataSourceConfig.java
⛳️ **작업한 브랜치**
- feature/#57
👷 **작업한 내용**
- Resolved: #57
=> [FIX] error 수정 - #57

chat-service/src/main/java/org/kiru/chat/adapter/in/web/ChatRoomController.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/ChatRoomRepositoryAdapter.java, chat-service/src/main/java/org/kiru/chat/application/port/in/GetChatRoomUseCase.java, chat-service/src/main/java/org/kiru/chat/application/port/out/GetChatRoomQuery.java, chat-service/src/main/java/org/kiru/chat/application/service/ChatService.java
⛳️ **작업한 브랜치**
- feature/#63
👷 **작업한 내용**
- Resolved: #63
=> [FIX] admin 권한 - #63

chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/ChatRoomRepositoryAdapter.java
⛳️ **작업한 브랜치**
- feature/#63
👷 **작업한 내용**
- Resolved: #63
=> [FIX] 트랜잭션 에러 - #63

chat-service/src/main/java/org/kiru/chat/adapter/in/web/WebSocketHandler.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/ChatRoomRepositoryAdapter.java, chat-service/src/main/java/org/kiru/chat/adapter/out/persistence/MessageRepositoryAdapter.java, chat-service/src/main/java/org/kiru/chat/application/port/out/SaveMessagePort.java, chat-service/src/main/java/org/kiru/chat/application/service/WebSocketUserService.java, chat-service/src/main/java/org/kiru/chat/config/redis/RedisSingleConfig.java, chat-service/src/main/java/org/kiru/chat/event/MessageCreateEvent.java, chat-service/src/main/java/org/kiru/chat/event/MessageDto.java, chat-service/src/main/java/org/kiru/chat/event/TranslateEventListener.java, core/src/main/java/org/kiru/core/chat/chatroom/domain/ChatRoom.java, core/src/main/java/org/kiru/core/chat/message/domain/Message.java, core/src/main/java/org/kiru/core/chat/message/entity/MessageJpaEntity.java
⛳️ **작업한 브랜치**
- feat/#73
👷 **작업한 내용**
- Resolved: #73
=> [fix] PR review  - #73

core/src/main/java/org/kiru/core/jwt/JwtProperties.java
⛳️ **작업한 브랜치**
- feature/#이슈번호
👷 **작업한 내용**
- Resolved: #75
=> [hotfix] error 수정 - #75

chat-service/src/main/java/org/kiru/chat/config/websocket/WebSocketConfig.java
⛳️ **작업한 브랜치**
- feature/#83
👷 **작업한 내용**
socketjs 제거 
- Resolved: #83
=> [del] socketjs 제거  - #83

user-service/src/main/java/org/kiru/user/user/dto/response/UserWithAdditionalInfoResponse.java
⛳️ **작업한 브랜치**
- fix/#85
👷 **작업한 내용**
변수명 변경
https://thirsty-lancer-467.notion.site/19fac207ea4680ada2e0ec51483faad0
- Resolved: #85
=> [FIX] portfolioUrl로 변경

user-service/src/main/java/org/kiru/user/portfolio/controller/PortfolioController.java, user-service/src/main/java/org/kiru/user/portfolio/service/PortfolioService.java
⛳️ **작업한 브랜치**
- feature/#111
👷 **작업한 내용**
- Resolved: #111
=> [FEAT] 유저 추천 할때 log 추가

alarm-service/src/main/java/org/kiru/alarm/config/FirebaseConfig.java
Reverts wakawaka-CONTACTO/contacto-server#176
=> Revert "[Fix] CD 진행 시 JSON  파싱 되도록 수정  - #175"

user-service/src/main/java/org/kiru/user/userlike/repository/UserLikeRepositoryConfig.java
⛳️ **작업한 브랜치**
- feature/#이슈번호
👷 **작업한 내용**
- Resolved: #이슈번호
=> refactor [#256] no change

discovery/src/main/java/org/kiru/discovery/DiscoveryApplication.java
⛳️ **작업한 브랜치**
- hotfix/#265
👷 **작업한 내용**
- Resolved: #265 @
=> [hotfix] ci/cd #265

alarm-service/src/main/java/org/kiru/alarm/AlarmServiceApplication.java, chat-service/src/main/java/org/kiru/chat/ChatServiceApplication.java, discovery/src/main/java/org/kiru/discovery/DiscoveryApplication.java, gateway-service/src/main/java/org/kiru/gateway/GatewayServiceApplication.java, user-service/src/main/java/org/kiru/user/UserServiceApplication.java
⛳️ **작업한 브랜치**
- feature/#267
👷 **작업한 내용**
- Resolved: #267
=> [hotfix] ci/cd #267

chat-service/src/main/java/org/kiru/chat/ChatServiceApplication.java
⛳️ **작업한 브랜치**
- feature/#이슈번호
👷 **작업한 내용**
- Resolved: #이슈번호
=> hotfix [#269] application.yml 파일 수정 반영
